# Makefile.dep created Sun May 23 00:34:18 PDT 2021
debug.o: debug.cpp debug.h util.h util.tcc
util.o: util.cpp debug.h util.h util.tcc
main.o: main.cpp listmap.h debug.h xless.h xpair.h listmap.tcc util.h \
 util.tcc
